CREATE PROCEDURE TransferFunds(FROM_ACC IN NUMBER,TO_ACC IN NUMBER,AMOUNT IN NUMBER)
AS
AVAIL_BAL NUMBER;
BEGIN
    SELECT BALANCE
    INTO AVAIL_BAL
    FROM ACCOUNTS
    WHERE ACCOUNTID = FROM_ACC;

    IF AVAIL_BAL > AMOUNT THEN

        UPDATE ACCOUNTS
        SET BALANCE = BALANCE - AMOUNT
        WHERE ACCOUNTID = FROM_ACC;

        UPDATE ACCOUNTS
        SET BALANCE = BALANCE + AMOUNT
        WHERE ACCOUNTID = TO_ACC;

        COMMIT;
    END IF;
END;
/
